[glossary]
= Glossary

BLOCK:: 
    A length of track of defined limits, the use of which by trains and engines is 
    governed by block signals, cab signals, or both. <<rot>>

BLOCK SIGNAL::
    A fixed signal at the entrance of a block to govern trains and engines entering 
    and using that block. <<rot>>

CURRENT OF TRAFFIC:: 
    The movement of trains on a main track, in one direction, specified by the rules. <<rot>> <<oprb>>

DIVISION::
    That portion of a railroad assigned to the supervision of a ______ (usually a 
    superintendent). <<rot>>
{nbsp} +
{nbsp} +
    That portion of a railroad assigned to the supervision of a Superintendent. <<oprb>>

ENGINE::
    A unit propelled by any form of energy, or a combination of such units, operated 
    from a single control, used in train or yard service. <<rot>>
{nbsp} +
{nbsp} +
    A machine propelled by any form of energy, and used in train or yard service. <<oprb>>

EXTRA TRAIN::
    A train not authorized by a time-table schedule.  It may be designated as -- 
{nbsp} +
        Extra--for any extra train except passenger extra or work extra;  +
        Passenger extra--for passenger train extra;  +
        Work extra--for work train extra. <<oprb>>

FIXED SIGNAL::
    A signal of fixed location indicating a condition affecting the movement of a 
    train or engine.
{nbsp} +
    Note.--The definition of a "Fixed Signal" covers such signals as switch, train order, block, interlocking, semaphore, disc, 
    ball, stop boards, yard limit boards, speed limit signs, slow boards or other means for displaying indications that govern 
    movement of a train or engine. <<oprb>>

MAIN TRACK::
    A track extending through yards and between stations, upon which trains are 
    operated by time-table, or train order, or both, or the use of which is governed by block signals. <<rot>>
{nbsp} +
{nbsp} +
    A track extending through yards and between stations, upon which trains are 
    operated by time-table or train order, or both, or the use of which is governed by block signals. <<oprb>>

MOTOR CAR::
    A car propelled by any form of energy, and used in train or yard service. <<oprb>>

PILOT::
    An employe assigned to a train when the engine-man or conductor, or both, are 
    not fully acquainted with the physical characteristics or rules of the railroad, or portion of the railroad over which the train is to be moved. <<rot>>
{nbsp} +
{nbsp} +
    An employee assigned to a train when the engineman or conductor, or both, are
    not fully acquainted with the physical characteristics or rules of the railroad, or portion of the railroad, over which the
    train is to be moved. <<oprb>>

REGULAR TRAIN::
    A train authorized by a time-table schedule. <<rot>> <<oprb>>

SCHEDULE::
    That part of a time-table which prescribes class, direction, number and movement for a regular train. <<rot>> <<oprb>>

SECTION::
    One of two or more trains running on the same schedule displaying signals, or for
    which signals are displayed. <<rot>>
{nbsp} +
{nbsp} +
    One of two or more trains running on the same schedule, displaying signals or
    for which signals are displayed. <<oprb>>

SIDING::
    A track auxiliary to the main track for meeting or passing trains. <<rot>> <<oprb>>

SINGLE TRACK::
    A main track upon which trains are operated in both directions. <<rot>> <<oprb>>

STATION::
    A place designated on the time-table by name. <<rot>> <<oprb>>

SUB-DIVISION::
    A portion of a division designated by time-table. <<oprb>>

SUBDIVISION::
    A portion of a division designated by time-table. <<rot>>

SUPERIOR TRAIN::
    A train having precedence over another train. <<rot>> <<oprb>>

TIME-TABLE::
    The authority for the movement of regular trains subject to the rules.  It 
    contains the classified schedules with special instructions relating to the movement of trains. <<rot>>
{nbsp} +
{nbsp} +
    The authority for the movement of regular trains subject to the rules.  It 
    contains classified schedules with special instructions relating to the movement of trains. <<oprb>>

TRAIN::
    An engine or more than one engine coupled, with or without cars, displaying
    markers. <<rot>>
{nbsp} +
{nbsp} +
    An engine, or motor car, or more than one engine, or motor car, coupled, with
    or without cars, displaying markers. <<oprb>>

TRAIN REGISTER::
    A book or form which may be used at designated stations for registering signals displayed, the time of arrival and departure of trains and such other information 
    as may be prescribed. <<rot>> <<oprb>>

TRAIN OF SUPERIOR CLASS::
    A train given precedence by time-table. <<rot>> <<oprb>>

TRAIN OF SUPERIOR DIRECTION::
    A train given precedence in the direction specified by time-table as between opposing trains of the same class. <<rot>> <<oprb>>

TRAIN OF SUPERIOR RIGHT::
    A train given precedence by train order. <<rot>> <<oprb>>

YARD::
    A system of tracks within defined limits provided for the making up of trains,
    storing of cars, and other purposes, over which movements not authorized by time-table, or by train order, may be made,
    subject to prescribed signals and rules, or special instructions. <<rot>>
{nbsp} +
{nbsp} +
    A system of tracks within defined limits provided for the making up of trains,
    storing of cars and other purposes, over which movements not authorized by timetable, or by train order, may be made, subject
    to prescribed signals and rules, or special instructions. <<oprb>>

YARD ENGINE::
    An engine assigned to yard service. <<rot>>
{nbsp} +
{nbsp} +
    An engine assigned to yard service and working within yard limits. <<oprb>>
