@startuml
hide footbox
skinparam monochrome true

actor Dispatcher as d
boundary "Selector\nCalling\nApparatus" as sca
control "Pole\nCharger\nRelay" as pcr
control "Selector A" as sa
control "Selector B" as sb
control "Selector C" as sc
actor "Agent C" as ac

activate d

d -> sca : operates selector key
activate sca

    sca -> pcr : send first pulse group
    activate pcr

        par
            pcr -> sa : pulses
            activate sa

                sa -> sa : advance code wheel
                activate sa
                sa --> sa
                deactivate sa

            sa --> pcr
        else
            pcr -> sb : pulses
            activate sb

                sb -> sb : advance code wheel
                activate sb
                sb --> sb
                deactivate sb

            sb --> pcr
        else
            pcr -> sc : pulses
            activate sc

                sc -> sc : advance code wheel
                activate sc
                sc --> sc
                deactivate sc

            sc --> pcr
        end par

    pcr --> sca
    deactivate pcr

    sca -> pcr : send second pulse group
    activate pcr

        par
            pcr -> sa : pulses

                sa -> sa : advance code wheel
                activate sa
                sa --> sa
                deactivate sa

            sa --> pcr
        else
            pcr -> sb : pulses

                sb -> sb : advance code wheel
                activate sb
                sb --> sb
                deactivate sb

            sb --> pcr
        else
            pcr -> sc : pulses

                sc -> sc : advance code wheel
                activate sc
                sc --> sc
                deactivate sc

            sc --> pcr
        end par

    pcr --> sca
    deactivate pcr

    sca -> pcr : send third pulse group
    activate pcr

        par
            pcr -> sa : pulses

                sa -> sa : advance code wheel
                activate sa
                sa --> sa

                sa -> sa : reset
                sa --> sa
                deactivate sa

            sa --> pcr
            deactivate sa
        else
            pcr -> sb : pulses

                sb -> sb : advance code wheel
                activate sb
                sb --> sb

                sb -> sb : reset
                sb --> sb
                deactivate sb

            sb --> pcr
            deactivate sb
        else
            pcr -> sc : pulses

                sc -> sc : advance code wheel
                activate sc
                sc --> sc

                sc -> ac : Ring!
                activate ac
                ac --> sc : Hello?
                deactivate sc

            sc --> pcr
        end par

        d -> ac : conversation
...
        ac -> d
        deactivate sc
        deactivate ac

    pcr --> sca
    deactivate pcr
@enduml
