name: CI

on:
  push:
    branches: [ master, develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.5'
        java-package: jdk
        architecture: x64
    - name: package
      run: mvn --file pom.xml
